import React from 'react';
import { TraitScores } from '@/lib/core/types';
import { Sparkles, ExternalLink, Compass, Briefcase, HeartHandshake } from 'lucide-react';

interface RecommendationCardProps {
  selfScores: TraitScores;
  peerScores: TraitScores;
}

export const RecommendationCard: React.FC<RecommendationCardProps> = ({\n  selfScores,\n  peerScores,\n}) => {\n  const o = peerScores.O ?? selfScores.O ?? 4.0;\n  const c = peerScores.C ?? selfScores.C ?? 4.0;\n  const e = peerScores.E ?? selfScores.E ?? 4.0;\n\n  let rec = {\n    badge: 'キャリア・適職',\n    icon: Briefcase,\n    title: 'あなたの強みが活きる「市場価値」を診断してみませんか？',\n    description: 'GAP-FIVEで判明したあなたの隠れた才能や対人適性は、ビジネスや転職市場でも大きな武器になります。無料の適職診断で、あなたにフィットする環境をチェック。',\n    ctaText: '無料で強み・年収診断を試す',\n    url: 'https://example.com/career-check', // アフィリエイトリンク差し替え可能\n  };\n\n  if (o >= 5.5) {\n    rec = {\n      badge: 'スキル・副業',\n      icon: Compass,\n      title: '知的好奇心と独創性を活かす「新しい働き方」',\n      description: '高い開放性（独創性・アイデア力）を持つあなたには、本業だけでなく個人のプロジェクトや副業でクリエイティビティを発揮する選択肢が適しています。',\n      ctaText: '未経験から学べるスキルアップ講座を見る',\n      url: 'https://example.com/skill-up',\n    };\n  } else if (e >= 5.0) {\n    rec = {\n      badge: '人脈・出会い',\n      icon: HeartHandshake,\n      title: '相性重視で気の合う仲間・パートナーを見つける',\n      description: '社交性と人当たりの良さを持つあなただからこそ、価値観や性格の相性がぴったり合うコミュニティやパートナーとの出会いで日常がさらに充実します。',\n      ctaText: '性格診断連動マッチングをチェック',\n      url: 'https://example.com/matching',\n    };\n  }\n\n  const Icon = rec.icon;\n\n  return (\n    <div className="bg-white rounded-3xl p-5 sm:p-6 shadow-sm border border-slate-100 space-y-3">\n      <div className="flex items-center justify-between">\n        <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-blue-50 text-blue-700 text-xs font-bold border border-blue-100">\n          <Icon className="w-3.5 h-3.5" />\n          <span>{rec.badge}</span>\n        </div>\n        <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">\n          PR / おすすめ\n        </span>\n      </div>\n\n      <div className="space-y-1">\n        <h3 className="text-sm sm:text-base font-bold text-slate-900 leading-snug">\n          {rec.title}\n        </h3>\n        <p className="text-xs text-slate-500 leading-relaxed">\n          {rec.description}\n        </p>\n      </div>\n\n      <div className="pt-1">\n        <a\n          href={rec.url}\n          target="_blank"\n          rel="noopener noreferrer nofollow"\n          className="inline-flex items-center justify-center gap-1.5 w-full py-3 px-4 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs shadow-sm transition-all hover:scale-[1.01]"\n        >\n          <span>{rec.ctaText}</span>\n          <ExternalLink className="w-3.5 h-3.5" />\n        </a>\n      </div>\n    </div>\n  );\n};\n